      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_01BE775FBD7B4B4CAE22DAC96B7A8163 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8ABABED9DDA04CFA98ED349DB7E34038 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F95D641A361C470CB1A586AB7C6F5AB5 }}

      - name: Azure WebApp Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: aihandwritingrec
          app-settings-json: |
            {
              "startupCommand": "bash startup.sh"
            }

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'nmitproj'
          slot-name: 'Production'
